CREATE DATABASE COMPRASWEB;
USE COMPRASWEB;

CREATE TABLE CLIENTE
(NIF VARCHAR(9),
 NOMBRE VARCHAR(40),
 APELLIDO VARCHAR(40),
 CP VARCHAR(5),
 DIRECCION VARCHAR(40),
 CIUDAD VARCHAR(40));
 
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (NIF); 

CREATE TABLE CATEGORIA
(ID_CATEGORIA VARCHAR(5),
 NOMBRE VARCHAR(40));
 
ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA); 

CREATE TABLE ALMACEN
(NUM_ALMACEN INTEGER,
 LOCALIDAD VARCHAR(40));
 
ALTER TABLE ALMACEN ADD CONSTRAINT PK_ALMACEN PRIMARY KEY (NUM_ALMACEN); 


CREATE TABLE PRODUCTO
(ID_PRODUCTO VARCHAR(5),
 NOMBRE VARCHAR(40),
 PRECIO DOUBLE,
 ID_CATEGORIA VARCHAR(5));

ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO); 

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA); 

CREATE TABLE COMPRA
(NIF VARCHAR(9),
 ID_PRODUCTO VARCHAR(5),
 FECHA_COMPRA DATE,
 UNIDADES INTEGER);
 
ALTER TABLE COMPRA ADD CONSTRAINT PK_COMPRA PRIMARY KEY (NIF,ID_PRODUCTO,FECHA_COMPRA);  
 
ALTER TABLE COMPRA ADD CONSTRAINT FK_COM_CLI FOREIGN KEY (NIF) REFERENCES CLIENTE(NIF);  

ALTER TABLE COMPRA ADD CONSTRAINT FK_COM_PRO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO); 

CREATE TABLE ALMACENA
(NUM_ALMACEN INTEGER,
 ID_PRODUCTO VARCHAR(5),
 CANTIDAD INTEGER);

ALTER TABLE ALMACENA ADD CONSTRAINT PK_ALMACENA PRIMARY KEY (NUM_ALMACEN,ID_PRODUCTO); 

ALTER TABLE ALMACENA ADD CONSTRAINT FK_ALM_ALM FOREIGN KEY (NUM_ALMACEN) REFERENCES ALMACEN(NUM_ALMACEN);  

ALTER TABLE ALMACENA ADD CONSTRAINT FK_ALM_PRO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO); 




-- Modificación realizada para ajustarse a los cambios del cliente

-- Sobre la tabla 'categoría', y claves ajenas
ALTER TABLE categoria MODIFY ID_CATEGORIA varchar(20);
ALTER TABLE categoria MODIFY NOMBRE varchar(800);
ALTER TABLE producto MODIFY ID_CATEGORIA varchar(20);

-- Sobre la tabla 'producto', y claves ajenas
ALTER TABLE producto MODIFY ID_PRODUCTO varchar(10);
ALTER TABLE producto MODIFY NOMBRE varchar(50);
ALTER TABLE compra MODIFY ID_PRODUCTO varchar(10);
ALTER TABLE almacena MODIFY ID_PRODUCTO varchar(10);
                     
-- Sobre la tabla 'compra', para admitir no solo Fecha, sino también Hora (CURRENT_TIMESTAMP);
ALTER TABLE compra MODIFY FECHA_COMPRA DATETIME;

-- Sobre la tabla 'cliente', para establecer nombre de usuario y contraseña:
ALTER TABLE cliente ADD USUARIO VARCHAR(40) NOT NULL;
ALTER TABLE cliente ADD PASSWORD VARCHAR(256) NOT NULL; -- VARCHAR de 256, por recomendación de la documentación de PHP sobre la función password_hash()
